title: Shankha Subhra Bag
description: Senior Shopify Developer with 10+ years of experience in Shopify Plus, Remix, React.js, Node.js, custom and public apps, headless commerce, and Hydrogen. Skilled in checkout customization, CRO, speed optimization, APIs, and integrations. Also experienced with Laravel, WordPress, BigCommerce, Squarespace and Wix.
theme: jekyll-theme-minimal
